version: "3.3"
services:
  frontend:
    container_name: kpd-frontend
    build: ./frontend
    restart:
      unless-stopped
    ports:
      - "8081:80"
  backend:
    container_name: kpd-backend
    build: ./backend
    networks:
      - backend-database
    restart: "unless-stopped"
    ports:
      - "4000:3001"
    env_file:
          - ./.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: "postgres"
    env_file:
      - ./.env
    networks:
      - backend-database
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
volumes:
  pg_data:
    driver: local

networks:
  backend-database: {}